GrumpyOldTroll/draft-jholland-quic-multicast

draft-jholland-quic-multicast.md

Some minor things I notice while reading and first attempt at adding ACK bundle size.
Would close #11

Add ACK Bundle Size

---

draft-jholland-quic-multicast.md

Thanks for the good document, I think it's a great start. I've got some minor fixes, including some typo corrections and a couple of attempts at rewording some sections that were difficult to parse. Let me know what you think.

Some suggested fixes

---

draft-jholland-quic-multicast.md

First attempt at stateless resets

---

draft-jholland-quic-multicast.md

Adding part about maintaining forward secrecy

---

draft-jholland-quic-multicast.md

(NB: I think this matches the implemented frames so far, did the work in parallel)

Issue #27 (frame spec cleanup)

---

draft-jholland-quic-multicast.md

Clarify that only SSM is supported

---

draft-jholland-quic-multicast.md

Add MC_RESERVE_CHANNEL_IDS frame

---

draft-jholland-quic-multicast.md

Fixed up text for MC_CHANNEL_LEAVE and state-changing.

---

draft-jholland-quic-multicast.md

Add text on connection termination

---

draft-jholland-quic-multicast.md

Only from the client point of view for now, I think server side might not actually be necessary because its very similar? (Basically just switch send/receive in front of the frames I think) 
Closes #50

Add channel state diagram

---

draft-jholland-quic-multicast.md

Will maybe require some changes depending on #58.
Not sure if its best to always include the ID and full frame names (makes it unnecessarily wide) 
Closes #51

First version of flow diagram

---

draft-jholland-quic-multicast.md

More for Michaels comments

---

draft-jholland-quic-multicast.md

Branched from the other PR, so better to merge that first to see the diff better. (Tried to avoid merge conflicts going forward)

Change MC_CHANNEL_PROPERTIES to MC_CHANNEL_KEY

---

draft-jholland-quic-multicast.md

draft-jholland-quic-multicast.md

---

draft-jholland-quic-multicast.md

shorten frame names and diagram widths (#69)

---

draft-jholland-quic-multicast.md

replace max idle time and ack bundle with max ack delay

---

draft-jholland-quic-multicast.md

text for 2 of the 3 points we (Max & I) discussed offline earlier today.
For the other point, I opened an issue with some tentative text and a discussion kickoff, but I'm not sure I've captured the right idea, so I'm leaving it open for a later rev:
https://github.com/GrumpyOldTroll/draft-jholland-quic-multicast/issues/75

touch up recovery and congestion control text

---

draft-jholland-quic-multicast.md

You won't believe this one cool trick that will change your life*
* not _that) cool, unlikely to change your life, might require
an update to your tooling

nits: hyperlink sections in other drafts

---

draft-jholland-quic-multicast.md

Closes #83, #84, #89, #90, #91 and #94

Adressing several of Lucas comments

---

draft-jholland-quic-multicast.md

Added server transport parameter

---

draft-jholland-quic-multicast.md

explain the requirements on key deletion

---

draft-jholland-quic-multicast.md

explain MC_INTEGRITY in channels/ref. merkle tree

---

draft-jholland-quic-multicast.md

Issues 104 and 105

---

draft-jholland-quic-multicast.md

Hello. Thank you for your interesting work. 
This draft is very interesting. I hope to be able to implement this.
Added the words "Channels only support source-specific multicast (SSM)".
I apologize in advance if this was unnecessary.

Change wording in Section 2

---

draft-jholland-quic-multicast.md

Closes #110 #113 #118 #120 and #121, also adds acknowledgements

Martins Review, in part
